@baseUrl=http://localhost:3500

###
POST {{baseUrl}}/user/signup
Content-Type: application/json

{
    "userName":"sugreev",
    "email":"sugreev@gmail.com",
    "password":123455,
    "role":"Admin",
    "phoneNumber":8930485009
}

###
POST {{baseUrl}}/user/signup/verify
Content-Type: application/json

{
    "email":"sugreev@gmail.com",
    "otp":480858
}

###
POST {{baseUrl}}/user/login
Content-Type: application/json

{
    "email":"sugreev@gmail.com",
    "password":"123455"
}

###
POST {{baseUrl}}/user/login/token
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.c3VncmVldkBnbWFpbC5jb20.fIcSSuyomh_syd5CMKI4zlQqmzQghNMgXaUvAqGBf48
