###
GET http://localhost:3005/question/getQuestion

###
POST http://localhost:3005/question/createQuestion?_id=64638176187e0b6b6f66f486
Content-Type: application/json

{
    "Title": " who is the  ceo of google",
    "Options": ["sundar","arayanmurthy","stevejobs","satya nadela"],
    "Answer":"a",
    "Type":"medium"
}

@baseUrl=http://localhost:3005
###
PUT {{baseUrl}}/question/updateQuestion/64647ebbc8bc50f9d606ed15/64637adb064052c62944fdf9
Content-Type: application/json

{
    "Title":"ceo of google",
    "Answer":"hfdh",
     "user":"64637adb064052c62944fdf9"
}


###
DELETE  {{baseUrl}}/question/deleteQuestion/6465cda5d6f9580ef92bffbe/64638176187e0b6b6f66f486
###