@baseUrl=http://localhost:3500

###
POST {{baseUrl}}/user/signup
Content-Type: application/json

{
    "userName":"sugreev",
    "email":"sugreev@gmail.com",
    "role":"Admin",
    "phoneNumber":8930485009
}

###
POST {{baseUrl}}/user/signup/verify
Content-Type: application/json

{
    "email":"sugreev@gmail.com",
    "otp":
}

###
POST {{baseUrl}}/user/login
Content-Type: application/json

{
    "email":"sugreev@gmail.com",
    "password":
}

###
POST {{baseUrl}}/user/login/token
Authorization: bearer 
